x = int(input())
a = input().split()
a_int = list(map(int, a))
a_set = set(a_int)
y = int(input())
b = input().split()
b_int = list(map(int, b))
b_set = set(b_int)
a_fin = a_set.difference(b_set)
b_fin = b_set.difference(a_set)
final_set = a_fin.union(b_fin)
final_list = list(final_set)
final_list.sort()
for el in final_list:
    print(el)
